version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
    volumes:
      - .data/:/var/lib/postgresql/data/
